version: "3.6"

services:

  dbm_mysql:
    image: mysql:latest
    volumes:
      - mysql-db:/var/lib/mysql
    restart: on-failure
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: athletic
      MYSQL_USER: root
      MYSQL_PASSWORD: root_password

volumes:
  mysql-db:
